version: "3.9"

services:
  app:
    extends:
      file: ./docker-compose.yml
      service: app
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && tail -f /dev/null"

  db:
    extends:
      file: ./docker-compose.yml
      service: db

volumes:
  dev-db-data:
  dev-static-data:
